### ISSUE TITLE
Add Information for Setting Up the Project on Command Line

### ISSUE THREAD

**Issue by lprc** [JuliBu/DecorumScenarioGenerator#1]
Executing `commands/run.py` does not work from command line out of the box (as suggested in the Readme). So maybe add the following information to the Readme for people who don't use PyCharme.

```bash
cd <path-to-project-root> # Go into project's root directory
python -m venv .venv # Create a virtual environment in .venv
source .venv/bin/activate # Activate virtual environment for the current session
export PYTHONPATH=<path-to-project-root> # Add search path, s.t. import-statements work
cd commands # For now, since relative paths are used in code
python run.py
```

The activation of the virtual environment and the `PYTHONPATH` update must happen every time a new terminal session is started.

Also a minimum python version (or at least the one with which this project is tested with) should be specified. At least the import statements only seem to work with 3.3+ ([See here](https://stackoverflow.com/a/63811406/4108363)).

**Comment by JuliBu** [comment]
Thanks! Is now part of the .readme!
