### ISSUE TITLE
Avoid Relative Paths in run.py

### ISSUE THREAD

**Issue by lprc** [JuliBu/DecorumScenarioGenerator#2]
Having relative paths in `commands/run.py`, e.g. line 180: `../new_scenarios/pdfs/<name>` results in the need to call `run.py` from inside `commands` subdirectory.

For Python 3 only, one possible solution would be to use:

```python
import pathlib
project_root_dir = pathlib.Path(__file__).parent.parent.resolve()
# ...
gen_pdf_version(all_conds, f"{project_root_dir}/new_scenarios/pdfs/<name>, ...)
```

Of course one has to be careful to remember adjusting this when the project layout changes, but which should hopefully not happen often, if anytime.

Source: [https://stackoverflow.com/a/3430395/4108363](https://stackoverflow.com/a/3430395/4108363)

**Comment by JuliBu** [comment]
Done! Thanks!
